/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AccessGrantsApi,
  BusinessMetricsApi,
  CostsApi,
  DashboardsApi,
  FiltersApi,
  FoldersApi,
  NotificationsApi,
  PingApi,
  PricesApi,
  SegmentsApi,
  TeamsApi,
  UsersApi,
  WorkspacesApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { VantageCustom } from "./client-custom";

export class Vantage extends VantageCustom {
  readonly accessGrants: AccessGrantsApi;
  readonly businessMetrics: BusinessMetricsApi;
  readonly costs: CostsApi;
  readonly dashboards: DashboardsApi;
  readonly filters: FiltersApi;
  readonly folders: FoldersApi;
  readonly notifications: NotificationsApi;
  readonly ping: PingApi;
  readonly prices: PricesApi;
  readonly segments: SegmentsApi;
  readonly teams: TeamsApi;
  readonly users: UsersApi;
  readonly workspaces: WorkspacesApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.accessGrants = new AccessGrantsApi(configuration);
    this.businessMetrics = new BusinessMetricsApi(configuration);
    this.costs = new CostsApi(configuration);
    this.dashboards = new DashboardsApi(configuration);
    this.filters = new FiltersApi(configuration);
    this.folders = new FoldersApi(configuration);
    this.notifications = new NotificationsApi(configuration);
    this.ping = new PingApi(configuration);
    this.prices = new PricesApi(configuration);
    this.segments = new SegmentsApi(configuration);
    this.teams = new TeamsApi(configuration);
    this.users = new UsersApi(configuration);
    this.workspaces = new WorkspacesApi(configuration);
  }

}
