/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccessGrant } from './access-grant';

/**
 * AccessGrants model
 * @export
 * @interface AccessGrants
 */
export interface AccessGrants {
    /**
     * 
     * @type {object}
     * @memberof AccessGrants
     */
    'links'?: object;
    /**
     * 
     * @type {Array<AccessGrant>}
     * @memberof AccessGrants
     */
    'access_grants'?: Array<AccessGrant>;
}

