/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * AccessGrant model
 * @export
 * @interface AccessGrant
 */
export interface AccessGrant {
    /**
     * 
     * @type {string}
     * @memberof AccessGrant
     */
    'token'?: string;
    /**
     * The token for any resource the AccessGrant is applied to.
     * @type {string}
     * @memberof AccessGrant
     */
    'resource_token'?: string;
    /**
     * The access status of the AccessGrant.
     * @type {string}
     * @memberof AccessGrant
     */
    'access'?: string;
    /**
     * The Team token for which an AccessGrant is applied to.
     * @type {string}
     * @memberof AccessGrant
     */
    'team_token'?: string;
    /**
     * The date and time, in UTC, the AccessGrant was created. ISO 8601 Formatted.
     * @type {string}
     * @memberof AccessGrant
     */
    'created_at'?: string;
    /**
     * The token for the User who created the AccessGrant.
     * @type {string}
     * @memberof AccessGrant
     */
    'created_by'?: string;
}

