/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BusinessMetricsUpdateValuesCsvRequest
 */
export interface BusinessMetricsUpdateValuesCsvRequest {
    /**
     * CSV file containing BusinessMetric dates and amounts
     * @type {Uint8Array | File | buffer.File}
     * @memberof BusinessMetricsUpdateValuesCsvRequest
     */
    'csv': Uint8Array | File | buffer.File;
}

