/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessMetric } from './business-metric';

/**
 * BusinessMetrics model
 * @export
 * @interface BusinessMetrics
 */
export interface BusinessMetrics {
    /**
     * 
     * @type {Array<BusinessMetric>}
     * @memberof BusinessMetrics
     */
    'business_metrics'?: Array<BusinessMetric>;
}

