/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * BusinessMetric model
 * @export
 * @interface BusinessMetric
 */
export interface BusinessMetric {
    /**
     * The title of the BusinessMetric.
     * @type {string}
     * @memberof BusinessMetric
     */
    'title'?: string;
    /**
     * The token of the BusinessMetric.
     * @type {string}
     * @memberof BusinessMetric
     */
    'token'?: string;
    /**
     * The token of the User who created the BusinessMetric.
     * @type {string}
     * @memberof BusinessMetric
     */
    'created_by_token'?: string;
    /**
     * The tokens for any CostReports that use the BusinessMetric, and the unit scale.
     * @type {Array<string>}
     * @memberof BusinessMetric
     */
    'cost_report_tokens_with_metadata'?: Array<string>;
    /**
     * The dates and amounts for the BusinessMetric
     * @type {Array<string>}
     * @memberof BusinessMetric
     */
    'values'?: Array<string>;
}

