/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Cost } from './cost';

/**
 * Costs model
 * @export
 * @interface Costs
 */
export interface Costs {
    /**
     * 
     * @type {object}
     * @memberof Costs
     */
    'links'?: object;
    /**
     * The sum of all costs for the CostReport for the requested period, rounded to 2 decimal places, alongside the ISO 4217 currency code.
     * @type {string}
     * @memberof Costs
     */
    'total_cost'?: string;
    /**
     * 
     * @type {Array<Cost>}
     * @memberof Costs
     */
    'costs'?: Array<Cost>;
}

