/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Cost
 */
export interface Cost {
    /**
     * The tag pairs attached to the cost that was incurred.
     * @type {Array<string>}
     * @memberof Cost
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof Cost
     */
    'links'?: object;
    /**
     * The date the cost was accrued. ISO 8601 Formatted.
     * @type {string}
     * @memberof Cost
     */
    'accrued_at'?: string;
    /**
     * The amount of the cost.
     * @type {string}
     * @memberof Cost
     */
    'amount'?: string;
    /**
     * The currency of the cost.
     * @type {string}
     * @memberof Cost
     */
    'currency'?: string;
    /**
     * The cost provider which incurred the cost.
     * @type {string}
     * @memberof Cost
     */
    'provider'?: CostProviderEnum;
    /**
     * The cost provider\'s billing account id that incurred the cost.
     * @type {string}
     * @memberof Cost
     */
    'billing_account_id'?: string;
    /**
     * The cost provider\'s account id that incurred the cost.
     * @type {string}
     * @memberof Cost
     */
    'account_id'?: string;
    /**
     * The service which incurred the cost.
     * @type {string}
     * @memberof Cost
     */
    'service'?: string;
    /**
     * The region which incurred the cost.
     * @type {string}
     * @memberof Cost
     */
    'region'?: string;
    /**
     * The resource id which incurred the cost.
     * @type {string}
     * @memberof Cost
     */
    'resource_id'?: string;
    /**
     * The tag attached to the cost that was incurred. DEPRECATED: does not support multiple tags.
     * @type {string}
     * @memberof Cost
     */
    'tag'?: string;
    /**
     * The category for the cost.
     * @type {string}
     * @memberof Cost
     */
    'cost_category'?: string;
    /**
     * The subcategory for the cost.
     * @type {string}
     * @memberof Cost
     */
    'cost_subcategory'?: string;
}

type CostProviderEnum = 'aws' | 'azure' | 'gcp' | 'snowflake' | 'databricks' | 'mongo' | 'datadog' | 'fastly' | 'new_relic' | 'opencost' | 'open_ai' | 'oracle' | 'confluent' | 'planetscale' | 'coralogix' | 'kubernetes'


