/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CostReportSettings } from './cost-report-settings';

/**
 * CostReport model
 * @export
 * @interface CostReport
 */
export interface CostReport {
    /**
     * The title of the CostReport.
     * @type {string}
     * @memberof CostReport
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CostReport
     */
    'token'?: string;
    /**
     * The token for the Folder the CostReport is a part of.
     * @type {string}
     * @memberof CostReport
     */
    'folder_token'?: string;
    /**
     * The tokens for the SavedFilters assigned to the CostReport.
     * @type {Array<string>}
     * @memberof CostReport
     */
    'saved_filter_tokens'?: Array<string>;
    /**
     * The tokens for the BusinessMetrics assigned to the CostReport, and the unit scale.
     * @type {Array<string>}
     * @memberof CostReport
     */
    'business_metric_tokens_with_metadata'?: Array<string>;
    /**
     * The filter applied to the CostReport. Additional documentation available at https://docs.vantage.sh/vql.
     * @type {string}
     * @memberof CostReport
     */
    'filter'?: string;
    /**
     * The grouping aggregations applied to the filtered data.
     * @type {string}
     * @memberof CostReport
     */
    'groupings'?: string;
    /**
     * 
     * @type {CostReportSettings}
     * @memberof CostReport
     */
    'settings'?: CostReportSettings;
    /**
     * The date and time, in UTC, the report was created. ISO 8601 Formatted.
     * @type {string}
     * @memberof CostReport
     */
    'created_at'?: string;
    /**
     * The token for the Workspace the CostReport is a part of.
     * @type {string}
     * @memberof CostReport
     */
    'workspace_token'?: string;
}

