/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CostReport } from './cost-report';

/**
 * CostReports model
 * @export
 * @interface CostReports
 */
export interface CostReports {
    /**
     * 
     * @type {object}
     * @memberof CostReports
     */
    'links'?: object;
    /**
     * 
     * @type {Array<CostReport>}
     * @memberof CostReports
     */
    'cost_reports'?: Array<CostReport>;
}

