/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Dashboard } from './dashboard';

/**
 * Dashboards model
 * @export
 * @interface Dashboards
 */
export interface Dashboards {
    /**
     * 
     * @type {object}
     * @memberof Dashboards
     */
    'links'?: object;
    /**
     * 
     * @type {Array<Dashboard>}
     * @memberof Dashboards
     */
    'dashboards'?: Array<Dashboard>;
}

