/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Dashboard model
 * @export
 * @interface Dashboard
 */
export interface Dashboard {
    /**
     * The title of the Dashboard.
     * @type {string}
     * @memberof Dashboard
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Dashboard
     */
    'token'?: string;
    /**
     * The tokens of the widgets displayed in the Dashboard. Currently only supports CostReport tokens.
     * @type {Array<string>}
     * @memberof Dashboard
     */
    'widget_tokens'?: Array<string>;
    /**
     * The tokens of the Saved Filters used in the Dashboard.
     * @type {Array<string>}
     * @memberof Dashboard
     */
    'saved_filter_tokens'?: Array<string>;
    /**
     * Determines how to group costs in the Dashboard.
     * @type {string}
     * @memberof Dashboard
     */
    'date_bin'?: DashboardDateBinEnum;
    /**
     * Determines the date range in the Dashboard. Guaranteed to be set to \'custom\' if \'start_date\' and \'end_date\' are set.
     * @type {string}
     * @memberof Dashboard
     */
    'date_interval'?: DashboardDateIntervalEnum;
    /**
     * The start date for the date range for CostReports in the Dashboard. ISO 8601 Formatted. Overwrites \'date_interval\' if set.
     * @type {string}
     * @memberof Dashboard
     */
    'start_date'?: string;
    /**
     * The end date for the date range for CostReports in the Dashboard. ISO 8601 Formatted. Overwrites \'date_interval\' if set.
     * @type {string}
     * @memberof Dashboard
     */
    'end_date'?: string;
    /**
     * The date and time, in UTC, the Dashboard was created. ISO 8601 Formatted.
     * @type {string}
     * @memberof Dashboard
     */
    'created_at'?: string;
    /**
     * The date and time, in UTC, the Dashboard was created. ISO 8601 Formatted.
     * @type {string}
     * @memberof Dashboard
     */
    'updated_at'?: string;
    /**
     * The token for the Workspace the Dashboard is a part of.
     * @type {string}
     * @memberof Dashboard
     */
    'workspace_token'?: string;
}

type DashboardDateBinEnum = 'cumulative' | 'day' | 'week' | 'month'
type DashboardDateIntervalEnum = 'this_month' | 'last_7_days' | 'last_30_days' | 'last_month' | 'last_3_months' | 'last_6_months' | 'custom' | 'last_12_months' | 'last_24_months' | 'last_36_months' | 'next_month' | 'next_3_months' | 'next_6_months' | 'next_12_months'


