/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Errors model
 * @export
 * @interface Errors
 */
export interface Errors {
    /**
     * 
     * @type {object}
     * @memberof Errors
     */
    'links'?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof Errors
     */
    'errors'?: Array<string>;
}

