/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Folder model
 * @export
 * @interface Folder
 */
export interface Folder {
    /**
     * The title of the Folder.
     * @type {string}
     * @memberof Folder
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    'token'?: string;
    /**
     * The token for the parent Folder, if any.
     * @type {string}
     * @memberof Folder
     */
    'parent_folder_token'?: string;
    /**
     * The tokens for the SavedFilters assigned to the Folder.
     * @type {Array<string>}
     * @memberof Folder
     */
    'saved_filter_tokens'?: Array<string>;
    /**
     * The date and time, in UTC, the Folder was created. ISO 8601 Formatted.
     * @type {string}
     * @memberof Folder
     */
    'created_at'?: string;
    /**
     * The date and time, in UTC, the Folder was last updated at. ISO 8601 Formatted.
     * @type {string}
     * @memberof Folder
     */
    'updated_at'?: string;
    /**
     * The token for the Workspace the Folder is a part of.
     * @type {string}
     * @memberof Folder
     */
    'workspace_token'?: string;
}

