/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Folder } from './folder';

/**
 * Folders model
 * @export
 * @interface Folders
 */
export interface Folders {
    /**
     * 
     * @type {object}
     * @memberof Folders
     */
    'links'?: object;
    /**
     * 
     * @type {Array<Folder>}
     * @memberof Folders
     */
    'folders'?: Array<Folder>;
}

