/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Create a SavedFilter for CostReports.
 * @export
 * @interface PostSavedFilters
 */
export interface PostSavedFilters {
    /**
     * The title of the SavedFilter.
     * @type {string}
     * @memberof PostSavedFilters
     */
    'title': string;
    /**
     * The Workspace to associate the SavedFilter with. Required if the API token is associated with multiple Workspaces.
     * @type {string}
     * @memberof PostSavedFilters
     */
    'workspace_token'?: string;
    /**
     * The filter query language to apply to the SavedFilter, which subsequently gets applied to a CostReport. Additional documentation available at https://docs.vantage.sh/vql.
     * @type {string}
     * @memberof PostSavedFilters
     */
    'filter'?: string;
}

