/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PostBusinessMetricsValuesInner
 */
export interface PostBusinessMetricsValuesInner {
    /**
     * 
     * @type {string}
     * @memberof PostBusinessMetricsValuesInner
     */
    'date': string;
    /**
     * 
     * @type {number}
     * @memberof PostBusinessMetricsValuesInner
     */
    'amount': number;
}

