/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Create a new Team.
 * @export
 * @interface PostTeams
 */
export interface PostTeams {
    /**
     * The description of the Team.
     * @type {string}
     * @memberof PostTeams
     */
    'description'?: string;
    /**
     * The name of the Team.
     * @type {string}
     * @memberof PostTeams
     */
    'name': string;
    /**
     * The Workspace tokens to associate to the Team.
     * @type {Array<string>}
     * @memberof PostTeams
     */
    'workspace_tokens'?: Array<string>;
    /**
     * The User tokens to associate to the Team.
     * @type {Array<string>}
     * @memberof PostTeams
     */
    'user_tokens'?: Array<string>;
    /**
     * The User emails to associate to the Team.
     * @type {Array<string>}
     * @memberof PostTeams
     */
    'user_emails'?: Array<string>;
    /**
     * The role to assign to the provided Users. Defaults to \'editor\' which has editor permissions.
     * @type {string}
     * @memberof PostTeams
     */
    'role'?: PostTeamsRoleEnum;
}

type PostTeamsRoleEnum = 'owner' | 'editor' | 'viewer'


