/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Create a Folder for CostReports.
 * @export
 * @interface PostFolders
 */
export interface PostFolders {
    /**
     * The title of the Folder.
     * @type {string}
     * @memberof PostFolders
     */
    'title': string;
    /**
     * The token of the parent Folder.
     * @type {string}
     * @memberof PostFolders
     */
    'parent_folder_token'?: string;
    /**
     * The tokens of the SavedFilters to apply to any Cost Report contained within the Folder.
     * @type {Array<string>}
     * @memberof PostFolders
     */
    'saved_filter_tokens'?: Array<string>;
    /**
     * The token of the Workspace to add the Folder to. Ignored if \'parent_folder_token\' is set. Required if the API token is associated with multiple Workspaces.
     * @type {string}
     * @memberof PostFolders
     */
    'workspace_token'?: string;
}

