/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Report settings configurable on top-level Segments.
 * @export
 * @interface PostSegmentsReportSettings
 */
export interface PostSegmentsReportSettings {
    /**
     * Reports created under this Segment will include credits.
     * @type {boolean}
     * @memberof PostSegmentsReportSettings
     */
    'include_credits'?: boolean;
    /**
     * Reports created under this Segment will include refunds.
     * @type {boolean}
     * @memberof PostSegmentsReportSettings
     */
    'include_refunds'?: boolean;
    /**
     * Reports created under this Segment will include discounts.
     * @type {boolean}
     * @memberof PostSegmentsReportSettings
     */
    'include_discounts'?: boolean;
    /**
     * Reports created under this Segment will include tax.
     * @type {boolean}
     * @memberof PostSegmentsReportSettings
     */
    'include_tax'?: boolean;
    /**
     * Reports created under this Segment will amortize.
     * @type {boolean}
     * @memberof PostSegmentsReportSettings
     */
    'amortize'?: boolean;
}

