/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PostBusinessMetricsCostReportTokensWithMetadataInner } from './post-business-metrics-cost-report-tokens-with-metadata-inner';
import { PostBusinessMetricsValuesInner } from './post-business-metrics-values-inner';

/**
 * Create a new Business Metric.
 * @export
 * @interface PostBusinessMetrics
 */
export interface PostBusinessMetrics {
    /**
     * The title of the Business Metric.
     * @type {string}
     * @memberof PostBusinessMetrics
     */
    'title': string;
    /**
     * The tokens for any CostReports that use the BusinessMetric, and the unit scale.
     * @type {Array<PostBusinessMetricsCostReportTokensWithMetadataInner>}
     * @memberof PostBusinessMetrics
     */
    'cost_report_tokens_with_metadata'?: Array<PostBusinessMetricsCostReportTokensWithMetadataInner>;
    /**
     * The dates and amounts for the BusinessMetric.
     * @type {Array<PostBusinessMetricsValuesInner>}
     * @memberof PostBusinessMetrics
     */
    'values'?: Array<PostBusinessMetricsValuesInner>;
}

