/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Create a ReportNotification.
 * @export
 * @interface PostReportNotifications
 */
export interface PostReportNotifications {
    /**
     * The title of the ReportNotification.
     * @type {string}
     * @memberof PostReportNotifications
     */
    'title': string;
    /**
     * The CostReport token.
     * @type {string}
     * @memberof PostReportNotifications
     */
    'cost_report_token': string;
    /**
     * The token of the Workspace to add the ReportNotification to. Required if the API token is associated with multiple Workspaces.
     * @type {string}
     * @memberof PostReportNotifications
     */
    'workspace_token'?: string;
    /**
     * The Users that receive the notification.
     * @type {Array<string>}
     * @memberof PostReportNotifications
     */
    'user_tokens'?: Array<string>;
    /**
     * The Slack or Microsoft Teams channels that receive the notification.
     * @type {Array<string>}
     * @memberof PostReportNotifications
     */
    'recipient_channels'?: Array<string>;
    /**
     * The frequency the ReportNotification is sent. Possible values: daily, weekly, monthly.
     * @type {string}
     * @memberof PostReportNotifications
     */
    'frequency': string;
    /**
     * The type of change the ReportNotification is tracking. Possible values: percentage, dollars.
     * @type {string}
     * @memberof PostReportNotifications
     */
    'change': string;
}

