/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Create an Access Grant.
 * @export
 * @interface PostAccessGrants
 */
export interface PostAccessGrants {
    /**
     * The token of the resource for which you are granting access.
     * @type {string}
     * @memberof PostAccessGrants
     */
    'resource_token': string;
    /**
     * The token of the Team you want to grant access to.
     * @type {string}
     * @memberof PostAccessGrants
     */
    'team_token': string;
    /**
     * The access level you want to grant. Defaults to \'allowed\'.
     * @type {string}
     * @memberof PostAccessGrants
     */
    'access'?: PostAccessGrantsAccessEnum;
}

type PostAccessGrantsAccessEnum = 'denied' | 'allowed'


