/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PostCostReportsBusinessMetricTokensWithMetadataInner } from './post-cost-reports-business-metric-tokens-with-metadata-inner';
import { PostCostReportsSettings } from './post-cost-reports-settings';

/**
 * Create a CostReport.
 * @export
 * @interface PostCostReports
 */
export interface PostCostReports {
    /**
     * The title of the CostReport.
     * @type {string}
     * @memberof PostCostReports
     */
    'title': string;
    /**
     * The token of the Workspace to add the Cost Report to. Ignored if \'folder_token\' is set. Required if the API token is associated with multiple Workspaces.
     * @type {string}
     * @memberof PostCostReports
     */
    'workspace_token'?: string;
    /**
     * Grouping values for aggregating costs on the report. Valid groupings: account_id, billing_account_id, charge_type, cost_category, cost_subcategory, provider, region, resource_id, service, tagged, tag:<tag_value>. If providing multiple groupings, join as comma separated values: groupings=provider,service,region
     * @type {string}
     * @memberof PostCostReports
     */
    'groupings'?: string;
    /**
     * The filter query language to apply to the CostReport. Additional documentation available at https://docs.vantage.sh/vql.
     * @type {string}
     * @memberof PostCostReports
     */
    'filter'?: string;
    /**
     * The tokens of the SavedFilters to apply to the CostReport.
     * @type {Array<string>}
     * @memberof PostCostReports
     */
    'saved_filter_tokens'?: Array<string>;
    /**
     * The tokens for any BusinessMetrics to attach to the CostReport, and the unit scale.
     * @type {Array<PostCostReportsBusinessMetricTokensWithMetadataInner>}
     * @memberof PostCostReports
     */
    'business_metric_tokens_with_metadata'?: Array<PostCostReportsBusinessMetricTokensWithMetadataInner>;
    /**
     * The token of the Folder to add the CostReport to. Determines the Workspace the report is assigned to.
     * @type {string}
     * @memberof PostCostReports
     */
    'folder_token'?: string;
    /**
     * 
     * @type {PostCostReportsSettings}
     * @memberof PostCostReports
     */
    'settings'?: PostCostReportsSettings;
}

