/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Price model
 * @export
 * @interface Price
 */
export interface Price {
    /**
     * 
     * @type {string}
     * @memberof Price
     */
    'id'?: string;
    /**
     * The unit in which the amount is billed.
     * @type {string}
     * @memberof Price
     */
    'unit'?: string;
    /**
     * The region the price is specific to.
     * @type {string}
     * @memberof Price
     */
    'region'?: string;
    /**
     * The part of the product the price applies to. (compute, transfer, etc..)
     * @type {string}
     * @memberof Price
     */
    'rate_type'?: string;
    /**
     * The currency of the amount.
     * @type {string}
     * @memberof Price
     */
    'currency'?: string;
    /**
     * The amount of money this specific product price costs.
     * @type {number}
     * @memberof Price
     */
    'amount'?: number;
    /**
     * Service specific metadata.
     * @type {object}
     * @memberof Price
     */
    'details'?: object;
}

