/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Price } from './price';

/**
 * Prices model
 * @export
 * @interface Prices
 */
export interface Prices {
    /**
     * 
     * @type {object}
     * @memberof Prices
     */
    'links'?: object;
    /**
     * 
     * @type {Array<Price>}
     * @memberof Prices
     */
    'prices'?: Array<Price>;
}

