/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Product } from './product';

/**
 * Products model
 * @export
 * @interface Products
 */
export interface Products {
    /**
     * 
     * @type {object}
     * @memberof Products
     */
    'links'?: object;
    /**
     * 
     * @type {Array<Product>}
     * @memberof Products
     */
    'products'?: Array<Product>;
}

