/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Update a SavedFilter for CostReports.
 * @export
 * @interface PutSavedFilters
 */
export interface PutSavedFilters {
    /**
     * The title of the SavedFilter.
     * @type {string}
     * @memberof PutSavedFilters
     */
    'title'?: string;
    /**
     * The filter query language to apply to the SavedFilter, which subsequently gets applied to a CostReport. Additional documentation available at https://docs.vantage.sh/vql.
     * @type {string}
     * @memberof PutSavedFilters
     */
    'filter'?: string;
}

