/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Update a Team.
 * @export
 * @interface PutTeams
 */
export interface PutTeams {
    /**
     * The description of the Team.
     * @type {string}
     * @memberof PutTeams
     */
    'description'?: string;
    /**
     * The name of the Team.
     * @type {string}
     * @memberof PutTeams
     */
    'name'?: string;
    /**
     * The Workspace tokens to associate to the Team.
     * @type {Array<string>}
     * @memberof PutTeams
     */
    'workspace_tokens'?: Array<string>;
    /**
     * The User tokens to associate to the Team.
     * @type {Array<string>}
     * @memberof PutTeams
     */
    'user_tokens'?: Array<string>;
    /**
     * The User emails to associate to the Team.
     * @type {Array<string>}
     * @memberof PutTeams
     */
    'user_emails'?: Array<string>;
    /**
     * The role to assign to the provided Users. Defaults to \'editor\' which has editor permissions.
     * @type {string}
     * @memberof PutTeams
     */
    'role'?: PutTeamsRoleEnum;
}

type PutTeamsRoleEnum = 'owner' | 'editor' | 'viewer'


