/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PostBusinessMetricsValuesInner } from './post-business-metrics-values-inner';
import { PutBusinessMetricsCostReportTokensWithMetadataInner } from './put-business-metrics-cost-report-tokens-with-metadata-inner';

/**
 * Updates an existing BusinessMetric.
 * @export
 * @interface PutBusinessMetrics
 */
export interface PutBusinessMetrics {
    /**
     * The title of the BusinessMetric.
     * @type {string}
     * @memberof PutBusinessMetrics
     */
    'title'?: string;
    /**
     * The tokens for any CostReports that use the BusinessMetric, and the unit scale.
     * @type {Array<PutBusinessMetricsCostReportTokensWithMetadataInner>}
     * @memberof PutBusinessMetrics
     */
    'cost_report_tokens_with_metadata'?: Array<PutBusinessMetricsCostReportTokensWithMetadataInner>;
    /**
     * The dates and amounts for the BusinessMetric.
     * @type {Array<PostBusinessMetricsValuesInner>}
     * @memberof PutBusinessMetrics
     */
    'values'?: Array<PostBusinessMetricsValuesInner>;
}

