/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PutCostReportsBusinessMetricTokensWithMetadataInner } from './put-cost-reports-business-metric-tokens-with-metadata-inner';
import { PutCostReportsSettings } from './put-cost-reports-settings';

/**
 * Update a CostReport.
 * @export
 * @interface PutCostReports
 */
export interface PutCostReports {
    /**
     * The title of the CostReport.
     * @type {string}
     * @memberof PutCostReports
     */
    'title'?: string;
    /**
     * Grouping values for aggregating costs on the report. Valid groupings: account_id, billing_account_id, charge_type, cost_category, cost_subcategory, provider, region, resource_id, service, tagged, tag:<tag_value>. If providing multiple groupings, join as comma separated values: groupings=provider,service,region
     * @type {string}
     * @memberof PutCostReports
     */
    'groupings'?: string;
    /**
     * The filter query language to apply to the CostReport. Additional documentation available at https://docs.vantage.sh/vql.
     * @type {string}
     * @memberof PutCostReports
     */
    'filter'?: string;
    /**
     * The tokens of the SavedFilters to apply to the CostReport.
     * @type {Array<string>}
     * @memberof PutCostReports
     */
    'saved_filter_tokens'?: Array<string>;
    /**
     * The tokens for any BusinessMetrics to attach to the CostReport, and the unit scale.
     * @type {Array<PutCostReportsBusinessMetricTokensWithMetadataInner>}
     * @memberof PutCostReports
     */
    'business_metric_tokens_with_metadata'?: Array<PutCostReportsBusinessMetricTokensWithMetadataInner>;
    /**
     * The token of the Folder to add the CostReport to. Determines the Workspace the report is assigned to.
     * @type {string}
     * @memberof PutCostReports
     */
    'folder_token'?: string;
    /**
     * 
     * @type {PutCostReportsSettings}
     * @memberof PutCostReports
     */
    'settings'?: PutCostReportsSettings;
}

