/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PostSegmentsReportSettings } from './post-segments-report-settings';

/**
 * Update a Segment.
 * @export
 * @interface PutSegments
 */
export interface PutSegments {
    /**
     * The title of the Segment.
     * @type {string}
     * @memberof PutSegments
     */
    'title'?: string;
    /**
     * The description of the Segment.
     * @type {string}
     * @memberof PutSegments
     */
    'description'?: string;
    /**
     * The priority of the Segment.
     * @type {number}
     * @memberof PutSegments
     */
    'priority'?: number;
    /**
     * Track Unallocated Costs which are not assigned to any of the created Segments.
     * @type {boolean}
     * @memberof PutSegments
     */
    'track_unallocated'?: boolean;
    /**
     * 
     * @type {PostSegmentsReportSettings}
     * @memberof PutSegments
     */
    'report_settings'?: PostSegmentsReportSettings;
    /**
     * The filter query language to apply to the Segment. Additional documentation available at https://docs.vantage.sh/vql.
     * @type {string}
     * @memberof PutSegments
     */
    'filter'?: string;
    /**
     * The token of the parent Segment this new Segment belongs to. Determines the Workspace the segment is assigned to.
     * @type {string}
     * @memberof PutSegments
     */
    'parent_segment_token'?: string;
}

