/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Update a Dashboard.
 * @export
 * @interface PutDashboards
 */
export interface PutDashboards {
    /**
     * The title of the Dashboard.
     * @type {string}
     * @memberof PutDashboards
     */
    'title'?: string;
    /**
     * The tokens of the widgets to add to the Dashboard. Currently only supports CostReport tokens.
     * @type {Array<string>}
     * @memberof PutDashboards
     */
    'widget_tokens'?: Array<string>;
    /**
     * The tokens of the Saved Filters used in the Dashboard.
     * @type {Array<string>}
     * @memberof PutDashboards
     */
    'saved_filter_tokens'?: Array<string>;
    /**
     * Determines how to group costs in the Dashboard.
     * @type {string}
     * @memberof PutDashboards
     */
    'date_bin'?: PutDashboardsDateBinEnum;
    /**
     * Determines the date range in the Dashboard. Incompatible with \'start_date\' and \'end_date\' parameters.
     * @type {string}
     * @memberof PutDashboards
     */
    'date_interval'?: PutDashboardsDateIntervalEnum;
    /**
     * The start date for the date range for costs in the Dashboard. ISO 8601 Formatted. Incompatible with \'date_interval\' parameter.
     * @type {string}
     * @memberof PutDashboards
     */
    'start_date'?: string;
    /**
     * The end date for the date range for costs in the Dashboard. ISO 8601 Formatted. Incompatible with \'date_interval\' parameter.
     * @type {string}
     * @memberof PutDashboards
     */
    'end_date': string;
}

type PutDashboardsDateBinEnum = 'cumulative' | 'day' | 'week' | 'month'
type PutDashboardsDateIntervalEnum = 'this_month' | 'last_7_days' | 'last_30_days' | 'last_month' | 'last_3_months' | 'last_6_months' | 'custom' | 'last_12_months' | 'last_24_months' | 'last_36_months' | 'next_month' | 'next_3_months' | 'next_6_months' | 'next_12_months'


