/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Update a ReportNotification.
 * @export
 * @interface PutReportNotifications
 */
export interface PutReportNotifications {
    /**
     * The title of the ReportNotification.
     * @type {string}
     * @memberof PutReportNotifications
     */
    'title'?: string;
    /**
     * The CostReport token.
     * @type {string}
     * @memberof PutReportNotifications
     */
    'cost_report_token'?: string;
    /**
     * The Users that receive the notification.
     * @type {Array<string>}
     * @memberof PutReportNotifications
     */
    'user_tokens'?: Array<string>;
    /**
     * The Slack or Microsoft Teams channels that receive the notification.
     * @type {Array<string>}
     * @memberof PutReportNotifications
     */
    'recipient_channels'?: Array<string>;
    /**
     * The frequency the ReportNotification is sent. Possible values: daily, weekly, monthly.
     * @type {string}
     * @memberof PutReportNotifications
     */
    'frequency'?: string;
    /**
     * The type of change the ReportNotification is tracking. Possible values: percentage, dollars.
     * @type {string}
     * @memberof PutReportNotifications
     */
    'change'?: string;
}

