/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Update a Folder for CostReports.
 * @export
 * @interface PutFolders
 */
export interface PutFolders {
    /**
     * The title of the Folder.
     * @type {string}
     * @memberof PutFolders
     */
    'title'?: string;
    /**
     * The token of the parent Folder.
     * @type {string}
     * @memberof PutFolders
     */
    'parent_folder_token'?: string;
    /**
     * The tokens of the SavedFilters to apply to any Cost Report contained within the Folder.
     * @type {Array<string>}
     * @memberof PutFolders
     */
    'saved_filter_tokens'?: Array<string>;
}

