/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Update an AccessGrant.
 * @export
 * @interface PutAccessGrants
 */
export interface PutAccessGrants {
    /**
     * Allowed or denied access to resource.
     * @type {string}
     * @memberof PutAccessGrants
     */
    'access': PutAccessGrantsAccessEnum;
}

type PutAccessGrantsAccessEnum = 'denied' | 'allowed'


