/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SavedFilter } from './saved-filter';

/**
 * SavedFilters model
 * @export
 * @interface SavedFilters
 */
export interface SavedFilters {
    /**
     * 
     * @type {object}
     * @memberof SavedFilters
     */
    'links'?: object;
    /**
     * 
     * @type {Array<SavedFilter>}
     * @memberof SavedFilters
     */
    'saved_filters'?: Array<SavedFilter>;
}

