/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SegmentReportSettings } from './segment-report-settings';

/**
 * Segment model
 * @export
 * @interface Segment
 */
export interface Segment {
    /**
     * The title of the Segment.
     * @type {string}
     * @memberof Segment
     */
    'title'?: string;
    /**
     * The description of the Segment.
     * @type {string}
     * @memberof Segment
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Segment
     */
    'token'?: string;
    /**
     * The token of the parent Segment of this Segment.
     * @type {string}
     * @memberof Segment
     */
    'parent_segment_token'?: string;
    /**
     * Track Unallocated Costs which are not assigned to any of the created Segments.
     * @type {boolean}
     * @memberof Segment
     */
    'track_unallocated'?: boolean;
    /**
     * 
     * @type {SegmentReportSettings}
     * @memberof Segment
     */
    'report_settings'?: SegmentReportSettings;
    /**
     * Costs are assigned in priority order across all Segments with assigned filters.
     * @type {number}
     * @memberof Segment
     */
    'priority'?: number;
    /**
     * The filter applied to the Segment. Additional documentation available at https://docs.vantage.sh/vql.
     * @type {string}
     * @memberof Segment
     */
    'filter'?: string;
    /**
     * The date and time, in UTC, the Segment was created. ISO 8601 Formatted.
     * @type {string}
     * @memberof Segment
     */
    'created_at'?: string;
    /**
     * The token for the Workspace the Segment is a part of.
     * @type {string}
     * @memberof Segment
     */
    'workspace_token'?: string;
}

