/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Segment } from './segment';

/**
 * Segments model
 * @export
 * @interface Segments
 */
export interface Segments {
    /**
     * 
     * @type {object}
     * @memberof Segments
     */
    'links'?: object;
    /**
     * 
     * @type {Array<Segment>}
     * @memberof Segments
     */
    'segments'?: Array<Segment>;
}

