/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Team } from './team';

/**
 * Teams model
 * @export
 * @interface Teams
 */
export interface Teams {
    /**
     * 
     * @type {object}
     * @memberof Teams
     */
    'links'?: object;
    /**
     * 
     * @type {Array<Team>}
     * @memberof Teams
     */
    'teams'?: Array<Team>;
}

