/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Team model
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * The description of the Team.
     * @type {string}
     * @memberof Team
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    'token'?: string;
    /**
     * The name of the Team.
     * @type {string}
     * @memberof Team
     */
    'name'?: string;
    /**
     * The tokens for any Workspaces that the Team belongs to
     * @type {Array<string>}
     * @memberof Team
     */
    'workspace_tokens'?: Array<string>;
    /**
     * The email addresses for Users that belong to the Team
     * @type {Array<string>}
     * @memberof Team
     */
    'user_emails'?: Array<string>;
    /**
     * The tokens for Users that belong to the Team
     * @type {Array<string>}
     * @memberof Team
     */
    'user_tokens'?: Array<string>;
}

