/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { User } from './user';

/**
 * Users model
 * @export
 * @interface Users
 */
export interface Users {
    /**
     * 
     * @type {object}
     * @memberof Users
     */
    'links'?: object;
    /**
     * 
     * @type {Array<User>}
     * @memberof Users
     */
    'users'?: Array<User>;
}

