/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * User model
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'token'?: string;
    /**
     * The name of the User.
     * @type {string}
     * @memberof User
     */
    'name'?: string;
    /**
     * The email of the User.
     * @type {string}
     * @memberof User
     */
    'email'?: string;
    /**
     * The role of the User.
     * @type {string}
     * @memberof User
     */
    'role'?: string;
}

