/*
Vantage

Vantage API

The version of the OpenAPI document: 2.0.0
Contact: support@vantage.sh

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Workspace } from './workspace';

/**
 * Workspaces model
 * @export
 * @interface Workspaces
 */
export interface Workspaces {
    /**
     * 
     * @type {object}
     * @memberof Workspaces
     */
    'links'?: object;
    /**
     * 
     * @type {Array<Workspace>}
     * @memberof Workspaces
     */
    'workspaces'?: Array<Workspace>;
}

